app/blueprints/auth.py
from flask import Blueprint, redirect, url_for, session, request, render_template
from functools import wraps
from flask_oauthlib.client import OAuth
import os

auth = Blueprint('auth', __name__)

oauth = OAuth(auth)

google = oauth.remote_app(
    'google',
    consumer_key=os.environ.get('YOUR_GOOGLE_CLIENT_ID'),
    consumer_secret=os.environ.get('YOUR_GOOGLE_CLIENT_SECRET'),
    request_token_params={'scope': 'email'},
    base_url='https://www.googleapis.com/oauth2/v1/userinfo',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://accounts.google.com/o/oauth2/token',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
)


@auth.route('/login')
def login():
    return render_template('login.html', show_modal=False)


@auth.route('/google_login')
def google_login():
    return google.authorize(callback=url_for('auth.login_callback', _external=True))


@auth.route('/logout')
def logout():
    session.pop('user')
    return redirect(url_for('home'))


@auth.route('/login/callback')
def login_callback():
    response = google.authorized_response()
    if response is None or response.get('access_token') is None:
        # Handle login error
        return 'Access denied: reason={} error={}'.format(
            request.args['error_reason'],
            request.args['error_description']
        )

    session['google_token'] = (response['access_token'], '')
    user_info = google.get('userinfo')
    session['user'] = user_info.data

    return redirect(url_for('home'))


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user' not in session:
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)

    return decorated_function


@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')

app/blueprints/black_scholes_calculator.py
import uuid
from datetime import datetime

import boto3
from flask import Blueprint, request, render_template, session

from blueprints.auth import login_required
from utils import black_scholes_call_option

from decimal import Decimal

from flask_limiter.util import get_remote_address
from flask_limiter import Limiter


black_scholes_limiter = Limiter(key_func=get_remote_address)

black_scholes_calculator = Blueprint('black_scholes_calculator', __name__, template_folder='../templates')

dynamodb = boto3.resource('dynamodb', region_name='us-west-1')
table = dynamodb.Table('UserCalculations')


# Adding login_required decorator for now, will implement API auth tokens later
@black_scholes_calculator.route('/api/calculate_option_price', methods=['GET'])
@black_scholes_limiter.limit("10 per minute")
def api_calculate_option_price():
    try:
        S = float(request.args.get('S'))
        K = float(request.args.get('K'))
        T = float(request.args.get('T'))
        r = float(request.args.get('r'))
        sigma = float(request.args.get('sigma'))

        option_price = black_scholes_call_option(S, K, T, r, sigma)

        return {'option_price': option_price}
    except (TypeError, ValueError):
        return {"error": "Invalid input. Please ensure all fields are numbers."}, 400


@black_scholes_calculator.route('/calculate_option_price', methods=['GET', 'POST'])
@login_required
def user_calculate_option_price():
    if request.method == 'POST':
        S = request.form.get('S')
        K = request.form.get('K')
        T = request.form.get('T')
        r = request.form.get('r')
        sigma = request.form.get('sigma')

        # Check if any field is empty
        if not all([S, K, T, r, sigma]):
            error_message = "Please fill in all fields."
            return render_template('black_scholes_calculator.html', error_message=error_message)

        # Convert form data to floats
        try:
            S = float(S)
            K = float(K)
            T = float(T)
            r = float(r)
            sigma = float(sigma)
        except ValueError:
            error_message = "Invalid input. Please ensure all fields are numbers."
            return render_template('black_scholes_calculator.html', error_message=error_message)

        # Calculate option price
        option_price = black_scholes_call_option(S, K, T, r, sigma)

        # Save the calculation to DynamoDB
        calculation_id = str(uuid.uuid4())
        table.put_item(
            Item={
                'user_id': session['user']['id'],
                'calculation_id': calculation_id,
                'calculation_type': 'option_price',
                'input_params': str((S, K, T, r, sigma)),
                'result': Decimal(str(option_price)),
                'created_at': str(datetime.utcnow())
            }
        )

        return render_template('black_scholes_calculator.html', option_price=option_price)

    return render_template('black_scholes_calculator.html')

app/blueprints/portfolio_risk_analysis.py
import uuid
from datetime import datetime

import boto3
from flask import Blueprint, request, render_template, session

from blueprints.auth import login_required
from utils import portfolio_risk_analysis

from decimal import Decimal

from flask_limiter.util import get_remote_address
from flask_limiter import Limiter

portfolio_risk_limiter = Limiter(key_func=get_remote_address)

portfolio_risk_calculator = Blueprint('portfolio_risk_calculator', __name__, template_folder='../templates')

dynamodb = boto3.resource('dynamodb', region_name='us-west-1')
table = dynamodb.Table('UserCalculations')


# Adding login_required decorator for now, will implement API auth tokens later
@portfolio_risk_calculator.route('/api/portfolio_risk_analysis', methods=['GET'])
@portfolio_risk_limiter.limit("10 per minute")
def api_calculate_portfolio_risk():
    try:
        stocks = request.args.get('stocks').split(',')
        weights = [float(weight) for weight in request.args.get('weights').split(',')]

        # Check if weights sum to 1
        if sum(weights) != 1:
            return {"error": "Weights must sum to 1."}, 400

        # Calculate portfolio risk
        portfolio_risk = portfolio_risk_analysis(stocks, weights)

        return {'portfolio_risk': portfolio_risk}
    except (TypeError, ValueError):
        return {"error": "Invalid input. Please ensure all fields are formatted correctly."}, 400


@portfolio_risk_calculator.route('/portfolio_risk_analysis', methods=['GET', 'POST'])
@login_required
def user_calculate_portfolio_risk():
    if request.method == 'POST':
        # Get form data
        stocks = request.form.get('stocks')
        weights = request.form.get('weights')

        # Check if any field is empty
        if not all([stocks, weights]):
            error_message = "Please fill in all fields."
            return render_template('portfolio_risk_analysis.html', error_message=error_message)

        # Convert form data to lists
        try:
            stocks = stocks.split(',')
            weights = [float(weight) for weight in weights.split(',')]
        except ValueError:
            error_message = "Invalid input. Please ensure all fields are formatted correctly."
            return render_template('portfolio_risk_analysis.html', error_message=error_message)

        # Check if weights sum to 1
        if sum(weights) != 1:
            error_message = "Weights must sum to 1."
            return render_template('portfolio_risk_analysis.html', error_message=error_message)

        # Calculate portfolio risk
        portfolio_risk = portfolio_risk_analysis(stocks, weights)

        # Save the calculation to DynamoDB
        calculation_id = str(uuid.uuid4())
        table.put_item(
            Item={
                'user_id': session['user']['id'],
                'calculation_id': calculation_id,
                'calculation_type': 'portfolio_risk',
                'input_params': str((stocks, weights)),
                'result': Decimal(str(portfolio_risk)),
                'created_at': str(datetime.utcnow())
            }
        )

        return render_template('portfolio_risk_analysis.html', portfolio_risk=portfolio_risk)

    return render_template('portfolio_risk_analysis.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Financial Calculator</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('black_scholes_calculator.user_calculate_option_price') }}">Black-Scholes Calculator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('portfolio_risk_calculator.user_calculate_portfolio_risk') }}">Portfolio Risk Calculator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('previous_calculations') }}">Previous Calculations</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if 'user' not in session %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.google_login') }}">Login with Google</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <div class="container py-5">
        <h1 class="text-center mb-4">{% block title %}{% endblock %}</h1>
        {% if show_modal is not defined or show_modal %} <!-- checks if modal should be shown -->
        <button type="button" class="btn btn-info mb-3" data-toggle="modal" data-target="#infoModal">
            How does this work?
        </button>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="infoModalLabel">How this Works</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% block modal_info %}{% endblock %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %} <!-- end conditional statement for whether to show modal -->

    <div class="container py-1">
        {% block content %}{% endblock %}
    </div>


</body>
</html>

templates/basecalculator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/style.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Financial Calculator</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('black_scholes_calculator.user_calculate_option_price') }}">Black-Scholes Calculator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('portfolio_risk_calculator.user_calculate_portfolio_risk') }}">Portfolio Risk Calculator</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if 'user' not in session %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.google_login') }}">Login with Google</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>


    <div class="container py-5">
        <h1 class="text-center mb-4">{% block title %}{% endblock %}</h1>
        {% if request.path != '/' %} <!-- how it works modal not necessary on home page -->
        <button type="button" class="btn btn-info mb-3" data-toggle="modal" data-target="#infoModal">
            How does this work?
        </button>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="infoModalLabel">How this Works</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% block modal_info %}{% endblock %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %} <!-- end conditional statement for hiding modal on homepage -->

    <div class="container py-1">
        {% block content %}{% endblock %}
    </div>


</body>
</html>

templates/black_scholes_calculator.html
{% extends "base.html" %}

{% block title %}
Option Price Calculator
{% endblock %}

{% block content %}
<form action="/calculate_option_price" method="post">
    <div class="form-group">
        <label for="S">Stock Price:</label>
        <input type="number" id="S" name="S" class="form-control">
    </div>
    <div class="form-group">
        <label for="K">Strike Price:</label>
        <input type="number" id="K" name="K" class="form-control">
    </div>
    <div class="form-group">
        <label for="T">Time to Maturity (in years):</label>
        <input type="number" id="T" name="T" class="form-control">
    </div>
    <div class="form-group">
        <label for="r">Risk-Free Rate (as decimal, e.g., 0.05 for 5%):</label>
        <input type="number" id="r" name="r" step="0.01" class="form-control">
    </div>
    <div class="form-group">
        <label for="sigma">Volatility of Underlying Asset (as decimal, e.g., 0.2 for 20%):</label>
        <input type="number" id="sigma" name="sigma" step="0.01" class="form-control">
    </div>
    <input type="submit" value="Calculate" class="btn btn-primary">
{% if error_message %}
<div class="alert alert-danger mt-4">
    {{ error_message }}
</div>
{% endif %}
</form>
{% if option_price %}
<div class="alert alert-success mt-4">
    The calculated option price is: {{ option_price }}
</div>
{% endif %}
{% endblock %}

{% block modal_info %}
This calculator uses the Black-Scholes formula to calculate the price of an option, which is a contract that gives the holder the right, but not the obligation, to buy or sell an underlying asset at a specified price before a certain date. The formula takes into account the current price of the asset, the strike price of the option, the time until the option expires, the risk-free rate, and the volatility of the underlying asset. The result is the theoretical fair value for the option.
{% endblock %}

templates/calculator.html
{% extends "basecalculator.html" %}

{% block title %}
Option Price Calculator
{% endblock %}

{% block content %}
<form action="/calculate_option_price" method="post">
    <div class="form-group">
        <label for="S">Stock Price:</label>
        <input type="number" id="S" name="S" class="form-control">
    </div>
    <div class="form-group">
        <label for="K">Strike Price:</label>
        <input type="number" id="K" name="K" class="form-control">
    </div>
    <div class="form-group">
        <label for="T">Time to Maturity (in years):</label>
        <input type="number" id="T" name="T" class="form-control">
    </div>
    <div class="form-group">
        <label for="r">Risk-Free Rate (as decimal, e.g., 0.05 for 5%):</label>
        <input type="number" id="r" name="r" step="0.01" class="form-control">
    </div>
    <div class="form-group">
        <label for="sigma">Volatility of Underlying Asset (as decimal, e.g., 0.2 for 20%):</label>
        <input type="number" id="sigma" name="sigma" step="0.01" class="form-control">
    </div>
    <input type="submit" value="Calculate" class="btn btn-primary">
{% if error_message %}
<div class="alert alert-danger mt-4">
    {{ error_message }}
</div>
{% endif %}
</form>
{% if option_price %}
<div class="alert alert-success mt-4">
    The calculated option price is: {{ option_price }}
</div>
{% endif %}
{% endblock %}

{% block modal_info %}
This calculator uses the Black-Scholes formula to calculate the price of an option, which is a contract that gives the holder the right, but not the obligation, to buy or sell an underlying asset at a specified price before a certain date. The formula takes into account the current price of the asset, the strike price of the option, the time until the option expires, the risk-free rate, and the volatility of the underlying asset. The result is the theoretical fair value for the option.
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}
    Welcome to Financial Calculators
{% endblock %}

{% block content %}
    <p class="text-center">Welcome to our financial calculators page! Choose one of the calculators from the navigation menu to get started, or login with Google.</p>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <form action="{{ url_for('auth.login_callback') }}" class="text-center" method="post">
        <a href="{{ url_for('auth.google_login') }}" class="btn btn-primary">Login with Google</a>
    </form>
{% endblock %}

templates/portfolio_risk_analysis.html
{% extends "base.html" %}

{% block title %}
Portfolio Risk Analysis
{% endblock %}

{% block content %}
<form action="/portfolio_risk_analysis" method="post">
    <div class="form-group">
        <label for="stocks">Stock Ticker Symbols (comma-separated):</label>
        <input type="text" id="stocks" name="stocks" class="form-control">
    </div>
    <div class="form-group">
        <label for="weights">Weights of Stocks in Portfolio (comma-separated, e.g., 0.5,0.3,0.2):</label>
        <input type="text" id="weights" name="weights" class="form-control">
    </div>
    <input type="submit" value="Calculate" class="btn btn-primary">
{% if error_message %}
<div class="alert alert-danger mt-4">
    {{ error_message }}
</div>
{% endif %}
</form>
{% if portfolio_risk %}
<div class="alert alert-success mt-4">
    The calculated portfolio risk (volatility) is: {{ portfolio_risk }}
</div>
{% endif %}
{% endblock %}

{% block modal_info %}
This calculator analyzes the risk of a portfolio based on the historical data of the selected stocks and their corresponding weights in the portfolio. The risk is measured as the portfolio's volatility, which is the standard deviation of the portfolio's returns. The result provides an indication of the portfolio's overall risk level.
{% endblock %}

templates/previous_calculations.html
{% extends "base.html" %}

{% block title %}Previous Calculations{% endblock %}

{% block modal_info %}
    View all the previous calculations performed using the Financial Calculator.
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Type of Calculation</th>
                <th>Input Parameters</th>
                <th>Result</th>
                <th>Date (UTC)</th>
            </tr>
        </thead>
        <tbody>
            {% for calculation in previous_calculations %}
                <tr>
                    <td>{{ calculation.calculation_type }}</td>
                    <td>{{ calculation.input_params }}</td>
                    <td>{{ calculation.result }}</td>
                    <td>{{ calculation.created_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if not previous_calculations %}
        <p>No previous calculations found.</p>
    {% endif %}
{% endblock %}